// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Apply: typeof import('./src/components/Mine/Apply.vue')['default']
    ApplyEdit: typeof import('./src/components/Mine/ApplyEdit.vue')['default']
    ArticleEdit: typeof import('./src/components/Mine/ArticleEdit.vue')['default']
    AttentionMessage: typeof import('./src/components/Chat/AttentionMessage.vue')['default']
    Car: typeof import('./src/components/Mine/Car.vue')['default']
    Chat: typeof import('./src/components/Mine/Chat.vue')['default']
    ChatDetail: typeof import('./src/components/Chat/ChatDetail.vue')['default']
    Collect: typeof import('./src/components/Mine/Collect.vue')['default']
    Comment: typeof import('./src/components/Comment.vue')['default']
    Course: typeof import('./src/components/Home/Course.vue')['default']
    Express: typeof import('./src/components/Discover/Express.vue')['default']
    ExpressAppend: typeof import('./src/components/Discover/ExpressAppend.vue')['default']
    ExpressDetail: typeof import('./src/components/Discover/ExpressDetail.vue')['default']
    Friend: typeof import('./src/components/Mine/Friend.vue')['default']
    History: typeof import('./src/components/Mine/History.vue')['default']
    Like: typeof import('./src/components/Mine/Like.vue')['default']
    LikeMessage: typeof import('./src/components/Chat/LikeMessage.vue')['default']
    Lost: typeof import('./src/components/Discover/Lost.vue')['default']
    LostAppend: typeof import('./src/components/Discover/LostAppend.vue')['default']
    LostDetail: typeof import('./src/components/Discover/LostDetail.vue')['default']
    Move: typeof import('./src/components/Move.vue')['default']
    Note: typeof import('./src/components/Forum/Note.vue')['default']
    NoteAppend: typeof import('./src/components/Forum/NoteAppend.vue')['default']
    NoteEdit: typeof import('./src/components/Mine/NoteEdit.vue')['default']
    Notice: typeof import('./src/components/Forum/Notice.vue')['default']
    NoticeDetail: typeof import('./src/components/Forum/NoticeDetail.vue')['default']
    Password: typeof import('./src/components/Mine/Password.vue')['default']
    Person: typeof import('./src/components/Person.vue')['default']
    Room: typeof import('./src/components/Home/Room.vue')['default']
    RoomApply: typeof import('./src/components/Home/RoomApply.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Sell: typeof import('./src/components/Discover/Sell.vue')['default']
    SellAppend: typeof import('./src/components/Discover/SellAppend.vue')['default']
    SellDetail: typeof import('./src/components/Discover/SellDetail.vue')['default']
    SellList: typeof import('./src/components/Discover/SellList.vue')['default']
    StarMessage: typeof import('./src/components/Chat/StarMessage.vue')['default']
    User: typeof import('./src/components/Home/User.vue')['default']
    UserInfo: typeof import('./src/components/Mine/UserInfo.vue')['default']
  }
}
